parser: babel-eslint
parserOptions:
    ecmaVersion: 9
    sourceType: module
extends: eslint:recommended
env:
    node: true
    es6: true
rules:
    indent:
        - error
        - 4
    semi:
        - error
        - never
    no-console: off
